niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 963584.5142112311
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_ring_1m_csi_2x0"
R50_mm = 10.48113773380731
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.14436567266131267
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 1006220
erfc_chi2_dof = 7.777070882173302
index = 67
status = "complete"
expected_events = 1.006992110945811e6
seed = 9000067
leaf = "del180s_ac300s_1Gy"
