niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 963584.5142112311
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_ring_1m_csi_2x0"
R50_mm = 10.394492353425564
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.14709894963921863
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 1007873
erfc_chi2_dof = 6.434831185993927
index = 38
status = "complete"
expected_events = 1.006992110945811e6
seed = 9000038
leaf = "del180s_ac300s_1Gy"
