conditional_count_variance = 573186.0028339836
mode = "washed"
R50_mm = 11.03430937550944
scanner = "crysp_ring_1m_csi_2x0"
R50_fit_error_mm = 0.145911618970237
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 601512
erfc_chi2_dof = 17.994738533145565
status = "complete"
window_s = [180.0, 300.0]
leaf = "del180s_ac300s_1Gy"
niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
dose_Gy = 1.0
stage = "ensemble"
schema = "statistical-procedure-v1"
index = 49
expected_events = 600642.8879732045
seed = 9000049
