niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 1.367758211267244e6
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_ring_1m_csi_2x0"
R50_mm = 11.0103001765143
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.1503531720093774
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 1433442
erfc_chi2_dof = 7.819435927194365
index = 16
status = "complete"
expected_events = 1.4342786777527735e6
seed = 9000016
leaf = "del120s_ac300s_1Gy"
