niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 526232.1418984679
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_ring_1m_csi_2x0"
R50_mm = 9.814846423968087
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.1562662031202912
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 548498
erfc_chi2_dof = 18.306977179397517
index = 65
status = "complete"
expected_events = 547474.6223154247
seed = 9000065
leaf = "del300s_ac300s_1Gy"
