niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r40_35_bgo_v2.toml"
topology = "closed"
crystal = "bgo_195k_2X0"
conditional_count_variance = 1.4224188731405633e6
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r40_35cm_bgo_2x0"
R50_mm = 11.080468722338646
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.2613302411978376
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 1491310
erfc_chi2_dof = 3.105286790298704
index = 2
status = "complete"
expected_events = 1.491603290721861e6
seed = 9000002
leaf = "del120s_ac300s_1Gy"
