niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_ring_bgo_v2.toml"
topology = "closed"
crystal = "bgo_195k_2X0"
conditional_count_variance = 6.627796289999995e6
dose_Gy = 1.0
mode = "nominal"
scanner = "crysp_ring_1m_bgo_2x0"
R50_mm = 10.962098896386351
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.15278849585923066
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 7367465
erfc_chi2_dof = 4.483354871668857
index = 93
status = "complete"
expected_events = 7.36421809999999e6
seed = 9000093
leaf = "del120s_ac300s_1Gy"
