niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_50_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 923204.9899520397
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_50cm_csi_2x0"
R50_mm = 11.253701611847127
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.20188784740619145
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 967217
erfc_chi2_dof = 3.3686866322616438
index = 46
status = "complete"
expected_events = 968105.298673956
seed = 9000046
leaf = "del120s_ac300s_1Gy"
