niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_50_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 923204.9899520397
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_50cm_csi_2x0"
R50_mm = 10.80878383780604
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.20904423607578065
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 967737
erfc_chi2_dof = 5.072871983821965
index = 73
status = "complete"
expected_events = 968105.298673956
seed = 9000073
leaf = "del120s_ac300s_1Gy"
