niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r40_50_bgo_v2.toml"
topology = "closed"
crystal = "bgo_195k_2X0"
conditional_count_variance = 2.0839477633525128e6
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r40_50cm_bgo_2x0"
R50_mm = 11.242970616110721
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.215264897045343
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 2183998
erfc_chi2_dof = 3.433000904120006
index = 36
status = "complete"
expected_events = 2.1853034013227853e6
seed = 9000036
leaf = "del120s_ac300s_1Gy"
