niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_ring_bgo_v2.toml"
topology = "closed"
crystal = "bgo_195k_2X0"
conditional_count_variance = 3.2560966846972797e6
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_ring_1m_bgo_2x0"
R50_mm = 10.856195464017546
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.15135390443492414
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 3411545
erfc_chi2_dof = 4.807087759237281
index = 3
status = "complete"
expected_events = 3.414458803321354e6
seed = 9000003
leaf = "del120s_ac300s_1Gy"
