niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_35_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 648188.851703094
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_35cm_csi_2x0"
R50_mm = 11.104677965880995
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.2306467325414382
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 679545
erfc_chi2_dof = 5.787329442576832
index = 28
status = "complete"
expected_events = 679715.0743318142
seed = 9000028
leaf = "del120s_ac300s_1Gy"
