niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_35_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 648188.851703094
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_35cm_csi_2x0"
R50_mm = 11.183064414868547
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.2233371419206978
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 678071
erfc_chi2_dof = 2.2775795537992685
index = 55
status = "complete"
expected_events = 679715.0743318142
seed = 9000055
leaf = "del120s_ac300s_1Gy"
