niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_35_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 648188.851703094
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_35cm_csi_2x0"
R50_mm = 10.942561838852031
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.23895731173378143
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 680142
erfc_chi2_dof = 3.4476780812197676
index = 24
status = "complete"
expected_events = 679715.0743318142
seed = 9000024
leaf = "del120s_ac300s_1Gy"
