niter = 50
config_path = "/Users/jjgomezcadenas/Projects/CryspBrainSim/config/run_parameters_r35_35_csi_v2.toml"
topology = "closed"
crystal = "csi_2X0"
conditional_count_variance = 648188.851703094
dose_Gy = 1.0
mode = "washed"
scanner = "crysp_r35_35cm_csi_2x0"
R50_mm = 11.085160954277272
schema = "statistical-procedure-v1"
stage = "ensemble"
R50_fit_error_mm = 0.22991628297010938
scenario = "uniform_headep_sobp_1e8"
backend = "metal"
events = 678073
erfc_chi2_dof = 4.646676369543118
index = 86
status = "complete"
expected_events = 679715.0743318142
seed = 9000086
leaf = "del120s_ac300s_1Gy"
