#!/usr/bin/env python3
"""Plot and export the paper's reference BGO statistical-procedure result."""

import math
import os
import tomllib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from crysp_paths import config_out
from fit_activity_profile import BLUE, INK, RED, SURFACE, style

SCENARIO = "uniform_headep_sobp_1e8"
TOPOLOGY = "closed"
SCANNER = "crysp_ring_1m_bgo_2x0"
CRYSTAL = "bgo_195k_2X0"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def gaussian(x, mean, sigma):
    return np.exp(-0.5 * ((x - mean) / sigma) ** 2) / (
        sigma * math.sqrt(2 * math.pi)
    )


def main():
    source = os.path.join(
        config_out(SCENARIO, TOPOLOGY, SCANNER, CRYSTAL),
        "statistical_procedure",
        "reference_bgo_t120.toml",
    )
    with open(source, "rb") as stream:
        result = tomllib.load(stream)
    shards = result["independent_shards"]
    thinning = result["thinning"]
    r_shards = np.asarray(shards["R50_mm"], dtype=float)
    r_nominal = np.asarray(thinning["nominal_R50_mm"], dtype=float)
    r_washed = np.asarray(thinning["washed_R50_mm"], dtype=float)

    fig, axes = plt.subplots(1, 2, figsize=(10.4, 4.2), facecolor=SURFACE)
    for axis in axes:
        style(axis)

    # With ten values, show every observation; the Gaussian is descriptive.
    axis = axes[0]
    bins = np.linspace(r_shards.min() - 0.04, r_shards.max() + 0.04, 6)
    axis.hist(r_shards, bins=bins, density=True, color=BLUE, alpha=0.30,
              edgecolor=BLUE, linewidth=1.0)
    x = np.linspace(bins[0], bins[-1], 300)
    axis.plot(x, gaussian(x, shards["mean_R50_mm"], shards["sigma_R_mm"]),
              color=BLUE, lw=2, label="Gaussian from sample mean and spread")
    rug_height = 0.035 * axis.get_ylim()[1]
    axis.vlines(r_shards, 0, rug_height, color=INK, lw=1.4)
    axis.set_title("(a) Ten independent 1-Gy shards", loc="left", color=INK)
    axis.set_xlabel("$R_{50}$ [mm]", color=INK)
    axis.set_ylabel("density", color=INK)
    axis.legend(frameon=False, fontsize=8, labelcolor=INK)

    axis = axes[1]
    combined = np.concatenate((r_nominal, r_washed))
    bins = np.linspace(combined.min(), combined.max(), 22)
    axis.hist(r_nominal, bins=bins, density=True, histtype="stepfilled",
              color=BLUE, alpha=0.24, label="nominal")
    axis.hist(r_washed, bins=bins, density=True, histtype="step",
              color=RED, linewidth=1.8, label="with washout")
    x = np.linspace(bins[0], bins[-1], 400)
    axis.plot(x, gaussian(x, thinning["nominal_mean_R50_mm"],
                          thinning["nominal_sigma_R_raw_mm"]),
              color=BLUE, lw=1.8)
    axis.plot(x, gaussian(x, thinning["washed_mean_R50_mm"],
                          thinning["washed_sigma_R_raw_mm"]),
              color=RED, lw=1.8)
    axis.set_title(f"(b) Fixed-pool thinning, N={result['realizations']}",
                   loc="left", color=INK)
    axis.set_xlabel("$R_{50}$ [mm]", color=INK)
    axis.set_ylabel("density", color=INK)
    axis.legend(frameon=False, fontsize=9, labelcolor=INK)
    fig.tight_layout()

    figure = os.path.join(REPO, "latex", "figs", "statistical_procedure_bgo.png")
    fig.savefig(figure, dpi=220, facecolor=SURFACE)
    plt.close(fig)

    macros = os.path.join(REPO, "latex", "statistical_procedure_results.tex")
    shard_error = np.asarray(shards["R50_fit_error_mm"], dtype=float)
    shard_chi2 = np.asarray(shards["erfc_chi2_dof"], dtype=float)
    nominal_chi2 = np.asarray(thinning["nominal_erfc_chi2_dof"], dtype=float)
    washed_chi2 = np.asarray(thinning["washed_erfc_chi2_dof"], dtype=float)
    lines = [
        "% Generated by tools/plot_statistical_procedure.py; do not edit.",
        rf"\newcommand{{\StatShardMean}}{{{shards['mean_R50_mm']:.3f}}}",
        rf"\newcommand{{\StatShardSigma}}{{{shards['sigma_R_mm']:.3f}}}",
        rf"\newcommand{{\StatShardFitErrMin}}{{{np.nanmin(shard_error):.3f}}}",
        rf"\newcommand{{\StatShardFitErrMax}}{{{np.nanmax(shard_error):.3f}}}",
        rf"\newcommand{{\StatShardChiMedian}}{{{np.nanmedian(shard_chi2):.2f}}}",
        rf"\newcommand{{\StatNomMean}}{{{thinning['nominal_mean_R50_mm']:.3f}}}",
        rf"\newcommand{{\StatNomRaw}}{{{thinning['nominal_sigma_R_raw_mm']:.3f}}}",
        rf"\newcommand{{\StatNomCorrection}}{{{thinning['nominal_finite_pool_correction']:.3f}}}",
        rf"\newcommand{{\StatNomCorrected}}{{{thinning['nominal_sigma_R_corrected_mm']:.3f}}}",
        rf"\newcommand{{\StatWashMean}}{{{thinning['washed_mean_R50_mm']:.3f}}}",
        rf"\newcommand{{\StatWashRaw}}{{{thinning['washed_sigma_R_raw_mm']:.3f}}}",
        rf"\newcommand{{\StatWashCorrection}}{{{thinning['washed_finite_pool_correction']:.3f}}}",
        rf"\newcommand{{\StatWashCorrected}}{{{thinning['washed_sigma_R_corrected_mm']:.3f}}}",
        rf"\newcommand{{\StatNomChiMedian}}{{{np.nanmedian(nominal_chi2):.2f}}}",
        rf"\newcommand{{\StatWashChiMedian}}{{{np.nanmedian(washed_chi2):.2f}}}",
        rf"\newcommand{{\StatNomFailures}}{{{thinning['n_fail_nominal']}}}",
        rf"\newcommand{{\StatWashFailures}}{{{thinning['n_fail_washed']}}}",
    ]
    with open(macros, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines) + "\n")
    print(f"wrote {figure}")
    print(f"wrote {macros}")


if __name__ == "__main__":
    main()
