#!/usr/bin/env python3
"""
plot_statproc_tbp_cafov.py — washed range precision sigma_R of the two BGO
scanner sizes (TBP ring 1 m vs CAFOV r40/35 cm) on the data-driven source,
across the five acquisition protocols. Bounded erfc fit, finite-pool-corrected,
N=100, 1 Gy; error bars from the stored +/-1/sqrt(2(N-1)) band.

Reads each scanner's <protocol>/combined/washed_N100.toml under
uniform_headep_sobp_1e8_dd/closed/<scanner>/bgo_195k_2X0/statistical_procedure/.

Writes latex/figs/statproc_tbp_cafov.png and latex/sigma_r_bgo_table.tex.
Run:  python3 tools/plot_statproc_tbp_cafov.py
"""
import os
import tomllib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from crysp_paths import config_out
from fit_activity_profile import BLUE, INK, RED, SURFACE, style

SCENARIO, TOPOLOGY, CRYSTAL = "uniform_headep_sobp_1e8_dd", "closed", "bgo_195k_2X0"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SCANNERS = [("TBP (ring 1 m)", "crysp_ring_1m_bgo_2x0", RED, "o"),
            ("CAFOV (35 cm)", "crysp_r40_35cm_bgo_2x0", BLUE, "s")]

# (label, delay/scan legend, case directory)
PROTOCOLS = [
    ("d120s300", "120 / 300", "del120s_ac300s_1Gy_D1p0Gy"),
    ("d180s300", "180 / 300", "del180s_ac300s_1Gy_D1p0Gy"),
    ("d300s300", "300 / 300", "del300s_ac300s_1Gy_D1p0Gy"),
    ("d120s120", "120 / 120", "del120s_ac300s_1Gy_D1p0Gy_t120_240"),
    ("d180s120", "180 / 120", "del180s_ac300s_1Gy_D1p0Gy_t180_300"),
]


def washed(scanner, case):
    p = os.path.join(config_out(SCENARIO, TOPOLOGY, scanner, CRYSTAL),
                     "statistical_procedure", case, "combined", "washed_N100.toml")
    with open(p, "rb") as fh:
        d = tomllib.load(fh)
    return d["corrected_sigma_R_mm"], d["relative_sigma_uncertainty"], d["mean_R50_mm"]


def main():
    x = np.arange(len(PROTOCOLS))
    data = {}
    fig, ax = plt.subplots(figsize=(7.4, 4.6), facecolor=SURFACE)
    style(ax)
    for i, (label, scanner, colour, marker) in enumerate(SCANNERS):
        sig, band = [], []
        for _, _, case in PROTOCOLS:
            s, b, r = washed(scanner, case)
            sig.append(s)
            band.append(b)
            data[(scanner, case)] = (s, r)
        sig, band = np.array(sig), np.array(band)
        ax.errorbar(x + (i - 0.5) * 0.12, sig, yerr=sig * band, fmt=marker,
                    ls="none", ms=8, color=colour, capsize=3, label=label)
    ax.axhline(1.0, color=INK, lw=0.8, ls=":", alpha=0.6)
    ax.set_xticks(x)
    ax.set_xticklabels([f"{lbl}\n{leg}" for lbl, leg, _ in PROTOCOLS], fontsize=9)
    ax.set_ylim(0.0, 0.30)
    ax.set_ylabel("washed $\\sigma_R$ at 1 Gy [mm]", color=INK, fontsize=13)
    ax.set_xlabel("acquisition protocol  (delay / scan, s)", color=INK, fontsize=11)
    ax.set_title("BGO range precision: TBP vs CAFOV, data-driven source",
                 color=INK, fontsize=12, loc="left")
    ax.legend(frameon=False, fontsize=12, labelcolor=INK, loc="upper left")
    fig.tight_layout()
    figpath = os.path.join(REPO, "latex", "figs", "statproc_tbp_cafov.png")
    fig.savefig(figpath, dpi=160, facecolor=SURFACE)
    plt.close(fig)
    print(f"wrote {figpath}")

    table = os.path.join(REPO, "latex", "sigma_r_bgo_table.tex")
    with open(table, "w", encoding="utf-8") as s:
        s.write("% Generated by tools/plot_statproc_tbp_cafov.py; do not edit.\n")
        s.write("\\begin{tabular}{lcccc}\n\\toprule\n")
        s.write("Protocol & delay/scan [s] & "
                "$\\sigma_R$ TBP & $\\sigma_R$ CAFOV & $R_{50}$ TBP/CAFOV [mm] \\\\\n"
                "\\midrule\n")
        for label, leg, case in PROTOCOLS:
            st, rt = data[("crysp_ring_1m_bgo_2x0", case)]
            sc, rc = data[("crysp_r40_35cm_bgo_2x0", case)]
            s.write(f"{label} & {leg} & {st:.3f} & {sc:.3f} & "
                    f"{rt:.2f} / {rc:.2f} \\\\\n")
        s.write("\\bottomrule\n\\end{tabular}\n")
    print(f"wrote {table}")

    for label, scanner, _, _ in SCANNERS:
        row = "  ".join(f"{data[(scanner, c)][0]:.3f}" for _, _, c in PROTOCOLS)
        print(f"{label:18s} sigma_R: {row}")


if __name__ == "__main__":
    main()
